# Generated by Django 4.0.4 on 2022-04-29 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=250)),
                ('language', models.IntegerField()),
                ('description', models.CharField(max_length=500)),
            ],
        ),
    ]
