# Generated by Django 4.0.4 on 2022-05-03 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_character'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='imgUrl',
            field=models.CharField(default=1, max_length=2048),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='character',
            name='description',
            field=models.CharField(max_length=100),
        ),
    ]
