# Generated by Django 4.0.4 on 2022-05-02 20:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_review_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.PositiveIntegerField(choices=[('1', '1:Very Bad'), ('2', '2:Bad'), ('1', '3:OK'), ('1', '4.Good'), ('1', '5.Excellent')], default='1', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
