# Generated by Django 4.0.4 on 2022-05-03 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_character_imgurl_alter_character_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='character',
            old_name='imgUrl',
            new_name='img_url',
        ),
    ]
