# Generated by Django 4.0.4 on 2022-05-03 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_rename_imgurl_character_img_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='quote',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
    ]
