# Generated by Django 4.0.4 on 2022-05-03 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_alter_review_rating'),
        ('main_app', '0006_character_quote'),
    ]

    operations = [
    ]
