# Generated by Django 4.0.4 on 2022-05-03 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_merge_0006_alter_review_rating_0006_character_quote'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='img_url',
            field=models.CharField(default=1, max_length=2048),
            preserve_default=False,
        ),
    ]
